Support setting web_schema
mailgun/mailgun-php pull request #755
Opened 2021-03-25 11:57 UTC by lekoala

As stated in curl api
https://documentation.mailgun.com/en/latest/api-domains.html#domains

and here
https://help.mailgun.com/hc/en-us/articles/360011566033-How-to-enable-HTTPS-tracking-links

i don't see put support in curl api so i didn't add it

2021-03-25 14:03 UTC, DavidGarciaCat commented
Hello @lekoala 

I cannot see this option on the Domains documentation page. Actually, the browser is unable to find it too:

![image](https://user-images.githubusercontent.com/7809429/112485060-6bd76b00-8d72-11eb-8ece-c2511aafe4b4.png)

Same point for the Support page content:

![image](https://user-images.githubusercontent.com/7809429/112485234-9cb7a000-8d72-11eb-9a7e-3fc95e929b39.png)

Can you point me out this feature, please?

Also, I cannot see any automated test to validate this behaviour.

Cheers,

2021-03-25 14:07 UTC, DavidGarciaCat requested changes

2021-03-25 14:07 UTC, DavidGarciaCat commented on src/Api/Domain.php
> +            Assert::stringNotEmpty($webScheme);
So, according to the API Documentation page, we have this:

![image](https://user-images.githubusercontent.com/7809429/112485785-32ebc600-8d73-11eb-9568-e6b340b31592.png)

At the moment, the `$webScheme` is quite open, as it allows "any" string. Ideally, it should be aligned to the two potential options, and we can set the by-default value too as part of the method's argument definition.

Please note the automated tests are not covering this update. They should be provided.

Cheers,

2021-04-30 20:36 UTC, DavidGarciaCat commented
Is this still relevant? There aren't further updates after my previous code review https://github.com/mailgun/mailgun-php/pull/755#pullrequestreview-621156003

2021-05-11 11:04 UTC, lekoala commented
@DavidGarciaCat yes it's still relevant. feel free to adjust it to your requirements it's probably going to be easier to add the changes yourself rather than having to validate or comment on whatever i might be doing ;)

2021-08-18 18:34 UTC, Nyholm commented
Hm. Thank you. 

Could you please add some tests to this PR and make sure the CI is green?

2021-08-19 09:36 UTC, lekoala commented
@Nyholm hey, i don't have time for this unfortunately. but feel free to add this change or run the test next time your make some change to the lib

2021-10-01 13:52 UTC, Pavlico commented
HI, i let myself add some tests, but couldnt add it to same request, @DavidGarciaCat can you look at #792

2021-10-04 14:07 UTC, DavidGarciaCat commented
I am going to close this MR as we are following this case on #792 

Cheers,

2021-10-04 14:07 UTC, closed without merging